# License: Commons Clause License Condition v1.0[LGPL-2.1-only]
# source (original): https://github.com/semgrep/semgrep-rules/blob/a3fef245/php/lang/security/mcrypt-use.yaml
# hash: a3fef245
rules:
  - id: php_mcrypt_rule-mcrypt-use
    patterns:
      - pattern: $FUNC(...);
      - metavariable-regex:
          metavariable: $FUNC
          regex: (mcrypt_|mdecrypt_).+
    message: Mcrypt functionality has been deprecated and/or removed in recent PHP
      versions. Consider using Sodium or OpenSSL.
    metadata:
      cwe: "CWE-676"
      shortDescription: "Use of potentially dangerous function"
      references:
        - https://www.php.net/manual/en/intro.mcrypt.php
        - https://github.com/FloeDesignTechnologies/phpcs-security-audit/blob/master/Security/Sniffs/BadFunctions/CryptoFunctionsSniff.php
      category: security
      owasp:
        - "A9:2017-Using Components with Known Vulnerabilities"
        - "A06:2021-Vulnerable and Outdated Components"
      technology:
        - php
      subcategory:
        - audit
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
      vulnerability_class:
        - Dangerous Method or Function
      security-severity: "MEDIUM"
    languages:
      - php
    severity: WARNING
