# yamllint disable
# License: MIT (c) GitLab Inc.
# yamllint enable
---
rules:
- id: "python_exec_rule-subprocess-call-array"
  languages:
  - "python"
  message: |
    subprocess call - check for execution of untrusted input
  patterns:
  - pattern: |
      subprocess.$FUNC([..., $ARG, ...])
  - metavariable-pattern:
      metavariable: "$ARG"
      patterns:
      - pattern-not: |
          "..."
      - pattern-not: |
          '...'
  metadata:
    cwe: "CWE-78"
    owasp:
    - "A1:2017-Injection"
    - "A03:2021-Injection"
    shortDescription: "Improper neutralization of special elements used in an OS Command
      ('OS Command Injection')"
    security-severity: "High"
    category: "security"
  severity: "WARNING"
