# todo
name: create_file
category: incident_response
tags: [binary_analysis, vulnerability_assessment, penetration_testing]
endpoint: api/files/create
description: 'Create a file with specified content on the HexStrike server. filename: Name of the file to create content:
  Content to write to the file binary: Whether the content is binary data'
returns: File creation results
parameters:
- name: filename
  type: string
  required: true
  description: Name of the file to create
- name: content
  type: string
  required: true
  description: Content to write to the file
- name: binary
  type: boolean
  required: false
  description: Whether the content is binary data
  default: false