# License: Commons Clause License Condition v1.0[LGPL-2.1-only]
# source (original): https://github.com/semgrep/semgrep-rules/blob/a3fef245/php/lang/security/ftp-use.yaml
# hash: a3fef245
rules:
  - id: php_ftp_rule-ftp-use
    patterns:
      - pattern: $FUNC(...);
      - metavariable-regex:
          metavariable: $FUNC
          regex: ftp_.+
    message: FTP allows for unencrypted file transfers. Consider using an encrypted
      alternative.
    metadata:
      cwe: "CWE-319"
      shortDescription: "Cleartext transmission of sensitive information"
      references:
        - https://www.php.net/manual/en/intro.ftp.php
        - https://github.com/FloeDesignTechnologies/phpcs-security-audit/blob/master/Security/Sniffs/BadFunctions/FringeFunctionsSniff.php
      category: security
      technology:
        - php
      owasp:
        - "A3:2017-Sensitive Data Exposure"
        - "A02:2021-Cryptographic Failures"
      subcategory:
        - audit
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
      vulnerability_class:
        - Mishandled Sensitive Information
      security-severity: "MEDIUM"
    languages:
      - php
    severity: WARNING
