# License: Commons Clause License Condition v1.0[LGPL-2.1-only]
# source (original): https://github.com/semgrep/semgrep-rules/blob/a3fef245/php/lang/security/backticks-use.yaml
# hash: a3fef245
rules:
  - id: php_backticks_rule-backticks-use
    pattern: "`...`;"
    message: Backticks use may lead to command injection vulnerabilities.
    metadata:
      cwe: "CWE-94"
      shortDescription: "Improper control of generation of code ('Code Injection')"
      references:
        - https://www.php.net/manual/en/language.operators.execution.php
        - https://github.com/FloeDesignTechnologies/phpcs-security-audit/blob/master/Security/Sniffs/BadFunctions/BackticksSniff.php
      category: security
      technology:
        - php
      owasp:
        - "A1:2017-Injection"
        - "A03:2021-Injection"
      cwe2022-top25: true
      subcategory:
        - audit
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
      vulnerability_class:
        - Code Injection
      security-severity: "CRITICAL"
    languages:
      - php
    severity: ERROR
