# yamllint disable
# License: Commons Clause License Condition v1.0[LGPL-2.1-only]
# source (original): https://github.com/semgrep/semgrep-rules/blob/release/java/spring/security/injection/tainted-file-path.yaml
# yamllint enable
rules:
- id: "java_traversal_rule-RelativePathTraversal"
  languages:
  - "java"
  message: |
    Detected user input controlling a file path. An attacker could control
    the location of this file, to include going backwards in the directory
    with '../'. 
    
    To address this, ensure that user-controlled variables in file
    paths are sanitized. You may also consider using a utility method such as
    org.apache.commons.io.FilenameUtils.getName(...) to only retrieve the file
    name from the path.
    
    Example of using `org.apache.commons.io.FilenameUtils.getName(...)` to 
    only retrieve the file name from the path
    ```
    String fileName = org.apache.commons.io.FilenameUtils.getName(userControlledInput);
    File file = new File("/path/to/directory/" + fileName);
    ```
  options:
    interfile: true
  severity: ERROR
  metadata:
    cwe: "CWE-23"
    shortDescription: "Relative Path Traversal"
    owasp:
    - "A01:2021-Broken Access Control"
    - "A5:2017-Broken Access Control"
    references:
    - https://owasp.org/www-community/attacks/Path_Traversal
    category: "security"
    security-severity: "CRITICAL"
    license: "Commons Clause License Condition v1.0[LGPL-2.1-only]"
  mode: taint
  pattern-sources:
  - patterns:
    - pattern-either:
      - pattern-inside: |
          $METHODNAME(..., @$REQ(...) $TYPE $SOURCE,...) {
            ...
          }
      - pattern-inside: |
          $METHODNAME(..., @$REQ $TYPE $SOURCE,...) {
            ...
          }
    - metavariable-regex:
        metavariable: $TYPE
        regex: ^(?!(Integer|Long|Float|Double|Char|Boolean|int|long|float|double|char|boolean))
    - metavariable-regex:
        metavariable: $REQ
        regex: (RequestBody|PathVariable|RequestParam|RequestHeader|CookieValue|ModelAttribute)
    - focus-metavariable: $SOURCE
  pattern-sinks:
  - patterns:
    - pattern-either:
      - pattern: new File(...)
      - pattern: new java.io.File(...)
      - pattern: new FileReader(...)
      - pattern: new java.io.FileReader(...)
      - pattern: new FileInputStream(...)
      - pattern: new java.io.FileInputStream(...)
      - pattern: (Paths $PATHS).get(...)
      - patterns:
        - pattern: |
            $CLASS.$FUNC(...)
        - metavariable-regex:
            metavariable: $FUNC
            regex: ^(getResourceAsStream|getResource)$
      - patterns:
        - pattern-either:
          - pattern: new ClassPathResource($FILE, ...)
          - pattern: ResourceUtils.getFile($FILE, ...)
          - pattern: new FileOutputStream($FILE, ...)
          - pattern: new java.io.FileOutputStream($FILE, ...)
          - pattern: new StreamSource($FILE, ...)
          - pattern: new javax.xml.transform.StreamSource($FILE, ...)
          - pattern: FileUtils.openOutputStream($FILE, ...)
        - focus-metavariable: $FILE
  pattern-sanitizers:
  - pattern: org.apache.commons.io.FilenameUtils.getName(...)
