# yamllint disable
# License: MIT (c) GitLab Inc.
# yamllint enable
---
rules:
- id: "scala_xml_rule-SAMLIgnoreComments"
  languages:
  - "scala"
  message: |
    Ignoring XML comments in SAML may lead to authentication bypass
  metadata:
    category: "security"
    shortDescription: "Weak authentication"
    cwe: "CWE-1390"
    security-severity: "Medium"
  pattern: "($POOL: BasicParserPool).setIgnoreComments(false);"
  severity: "WARNING"
