# License: Commons Clause License Condition v1.0[LGPL-2.1-only]
# source (original): https://github.com/semgrep/semgrep-rules/blob/a3fef245/php/lang/security/eval-use.yaml
# hash: a3fef245
rules:
  - id: php_eval_rule-eval-use
    patterns:
      - pattern: eval(...);
      - pattern-not: eval('...');
    message: Evaluating non-constant commands. This can lead to command injection.
    metadata:
      cwe: "CWE-78"
      shortDescription: "Improper neutralization of special elements used in an OS command ('OS Command Injection')"
      references:
        - https://www.php.net/manual/en/function.eval
        - https://github.com/FloeDesignTechnologies/phpcs-security-audit/blob/master/Security/Sniffs/BadFunctions/NoEvalsSniff.php
      category: security
      technology:
        - php
      owasp:
        - "A1:2017-Injection"
        - "A03:2021-Injection"
      cwe2022-top25: true
      cwe2021-top25: true
      subcategory:
        - audit
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
      vulnerability_class:
        - Command Injection
      security-severity: "CRITICAL"
    languages:
      - php
    severity: ERROR
