# yamllint disable
# License: GNU Lesser General Public License v3.0
# source (original): https://github.com/ajinabraham/njsscan/blob/master/njsscan/rules/semantic_grep/jwt/jwt_express_hardcoded.yaml
# hash: e7a0a61
# yamllint enable
---
rules:
- id: "rules_lgpl_javascript_jwt_rule-jwt-express-hardcoded"
  patterns:
  - pattern-either:
    - pattern-inside: |
        import { ..., $JWT,... } from 'express-jwt';
        ...
    - pattern-inside: |
        var {..., expressjwt: $JWT,... } = require('express-jwt');
        ...
  - pattern-either:
    - pattern: $JWT(<...{...,secret:"...",...}...>)
    - patterns:
      - pattern-inside: |
          $OPTS = <... {secret: "..."} ...>;
          ...
      - pattern: "$JWT(<... $OPTS ...>,...)"
    - patterns:
      - pattern-inside: |
          $OPTS = <... {secret: "..."} ...>;
          ...
          $OPTS2 = <... $OPTS ...>;
          ...
      - pattern: "$JWT(<... $OPTS2 ...>,...)"
  message: |
    Hardcoded JWT secret or private key was found. Hardcoding secrets like JWT signing keys poses a significant security risk. 
    If the source code ends up in a public repository or is compromised, the secret is exposed. Attackers could then use the secret to 
    generate forged tokens and access the system. Store it properly in an environment variable.

    Here are some recommended safe ways to access JWT secrets:
      - Use environment variables to store the secret and access it in code instead of hardcoding. This keeps it out of source control.
      - Use a secrets management service to securely store and tightly control access to the secret. Applications can request the secret at runtime.
      - For local development, use a .env file that is gitignored and access the secret from process.env.

    sample code snippet of accessing JWT secret from env variables
    ```
    router.route("/auth-route-1").get(
      jwt({ secret: process.env.secret, algorithms: ['HS256'] }),
        (req, res) => {
            res.send('Token is valid');
        }
    );
    ```
  severity: "ERROR"
  languages:
  - "javascript"
  metadata:
    owasp: 
    - "A3:2017-Sensitive Data Exposure"
    - "A02:2021-Cryptographic Failures"
    cwe: "CWE-522"
    shortDescription: "Insufficiently protected credentials"
    security-severity: "CRITICAL"
    category: "security"
