# License: Commons Clause License Condition v1.0[LGPL-2.1-only]
# source (original): https://github.com/semgrep/semgrep-rules/blob/a3fef245/php/lang/security/exec-use.yaml
# hash: a3fef245
rules:
  - id: php_exec_rule-exec-use
    patterns:
      - pattern: $FUNC(...);
      - pattern-not: $FUNC('...', ...);
      - metavariable-regex:
          metavariable: $FUNC
          regex: exec|passthru|proc_open|popen|shell_exec|system|pcntl_exec
    message: Executing non-constant commands. This can lead to command injection.
    metadata:
      cwe: "CWE-94"
      shortDescription: "Improper control of generation of code ('Code Injection')"
      references:
        - https://github.com/FloeDesignTechnologies/phpcs-security-audit/blob/master/Security/Sniffs/BadFunctions/SystemExecFunctionsSniff.php
      category: security
      technology:
        - php
      owasp:
        - "A1:2017-Injection"
        - "A03:2021-Injection"
      cwe2022-top25: true
      subcategory:
        - audit
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
      vulnerability_class:
        - Code Injection
      security-severity: "CRITICAL"
    languages:
      - php
    severity: ERROR
