# License: Commons Clause License Condition v1.0[LGPL-2.1-only]
# source (original): https://github.com/semgrep/semgrep-rules/blob/a3fef245/php/lang/security/phpinfo-use.yaml
# hash: a3fef245
rules:
  - id: php_phpinfo_rule-phpinfo-use
    pattern: phpinfo(...);
    message: The 'phpinfo' function may reveal sensitive information about your
      environment.
    metadata:
      cwe: "CWE-497"
      shortDescription: "Exposure of sensitive system information to an unauthorized control sphere"
      references:
        - https://www.php.net/manual/en/function.phpinfo
        - https://github.com/FloeDesignTechnologies/phpcs-security-audit/blob/master/Security/Sniffs/BadFunctions/PhpinfosSniff.php
      category: security
      technology:
        - php
      owasp:
        - "A5:2017-Broken Access Control"
        - "A01:2021-Broken Access Control"
      cwe2021-top25: true
      subcategory:
        - vuln
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
      vulnerability_class:
        - Mishandled Sensitive Information
      security-severity: "MEDIUM"
    languages:
      - php
    severity: WARNING
