# yamllint disable
# License: Commons Clause License Condition v1.0[LGPL-2.1-only]
# yamllint enable
---
rules:
- id: "ruby_ssl_rule-ForceSSLFalse"
  pattern: config.force_ssl = false
  fix-regex:
    regex: =\s*false
    replacement: = true
  message: |
    The application was found setting `force_ssl` to `false`. This setting
    can expose the application to the risk of network
    interception of unencrypted traffic. Enabling `force_ssl` by setting 
    `config.force_ssl = true` in the application's configuration, specifically 
    within `config/environments/production.rb`, forces the use of HTTPS, 
    encrypting data in transit and safeguarding against eavesdropping or data 
    tampering. 
  languages:
  - "ruby"
  severity: "WARNING"
  metadata:
    cwe: "CWE-319"
    shortDescription: "Cleartext transmission of sensitive information"
    category: "security"
    owasp:
    - "A3:2017-Sensitive Data Exposure"
    - "A04:2021-Insecure Design"
    security-severity: "MEDIUM"
    technology:
    - "ruby"
    references:
    - "https://github.com/semgrep/semgrep-rules/blob/develop/ruby/lang/security/force-ssl-false.yaml"

  