# yamllint disable
# License: GNU Lesser General Public License v3.0
# source (original): https://find-sec-bugs.github.io/bugs.htm
# yamllint enable
---
rules:
  - id: "kotlin_crypto_rule-WeakTLSProtocolVersion"
    languages:
      - "kotlin"
    message: |
      The application was found enabling insecure TLS protocol versions. When enabling protocol
      versions for an `SSLContext`, only the following versions should be allowed:
      - TLSv1.2
      - TLSv1.3
      - DTLSv1.2
      - DTLSv1.3

      To mitigate potential security risks, it is strongly advised to enforce TLS 1.2 as the minimum
      protocol version and disallow older versions such as TLS 1.0. Do note that newer versions of
      Java do not even support TLS 1.0 and will throw `NoSuchAlgorithmException`. Versions of TLS
      prior to 1.2 could expose the connection to downgrade attacks, where an adversary intercepts
      the
      connection and alters the requested protocol version to be a less secure one.

      In many scenarios, relying on the default system configuration does not meet compliance
      standards. This is due to the application being deployed across diverse systems with varying
      configurations and Java versions. While the default value may be secure on modern and
      up-to-date systems, it may not hold true for older systems. Consequently, it is highly
      recommended to explicitly define a secure configuration in all cases.

      Example configuring an SSLContext with TLSv1.2:
      ```
      // Create an SSLContext with TLSv1.2 explicitly
      SSLContext tlsContext = SSLContext.getInstance("TLSv1.2"); // or TLSv1.3, DTLSv1.2, DTLSv1.3

      // Alternatively, set the enabled protocols
      SSLContext serverSslContext = SSLContext.getInstance("TLS");
      SSLEngine serverEngine = serverSslContext.createSSLEngine();
      // Calling setEnabledProtocols will override the original context's configured protocol version
      serverEngine.setEnabledProtocols(new String[]{ "TLSv1.2" });
      ```

      For more information on `SSLContext` see:
      - https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/SSLContext.html

      For more information on MiTM attacks see:
      - https://owasp.org/www-community/attacks/Manipulator-in-the-middle_attack
    metadata:
      shortDescription: "Inadequate encryption strength"
      category: "security"
      cwe: "CWE-326"
      owasp:
        - "A3:2017-Sensitive Data Exposure"
        - "A02:2021-Cryptographic Failures"
      security-severity: "MEDIUM"
    severity: "WARNING"

    patterns:
      - pattern-either:
          - pattern-inside: |
              import javax.net.ssl.*;
              ...
          - pattern-inside: |
              import javax.net.ssl.SSLContext;
              ...
      - pattern-either:
          - pattern-inside: |
              SSLContext.getInstance("$UNSAFE_VERSION");
          - pattern-inside: |
              SSLContext.getInstance(...);
              ...
              $ENGINE.setEnabledProtocols(arrayOf(...,"$UNSAFE_VERSION",...));
      - pattern-not:
          patterns:
            - pattern-inside: |
                $C = SSLContext.getInstance(...);
                ...
                $ENGINE.setEnabledProtocols(arrayOf(...,"$DT_GOODNESS",...));
            - metavariable-regex:
                metavariable: "$DT_GOODNESS"
                regex: "^D?TLSv1\\.[23]$"
      - pattern-not:
          patterns:
            - pattern-inside: |
                $C = SSLContext.getInstance(...);
                ...
                $E = $C.createSSLEngine()
                ...
                $E.enabledProtocols = arrayOf(...,"$DT_GOODNESS",...)
            - metavariable-regex:
                metavariable: "$DT_GOODNESS"
                regex: "^DTLSv1\\.[23]$"
      - metavariable-regex:
          metavariable: "$UNSAFE_VERSION"
          regex: "^(TLS|(D)?TLSv1.(0|1))$"
