# yamllint disable
# License: GNU Lesser General Public License v3.0
# source (original): https://find-sec-bugs.github.io/bugs.htm
# yamllint enable
---
rules:
  - id: "kotlin_password_rule-ConstantDBPassword"
    pattern: 'java.sql.DriverManager.getConnection($URI, $USR, "...")'
    message: |
      A potential hard-coded password was identified in a database connection string.
      Passwords should not be stored directly in code
      but loaded from secure locations such as a Key Management System (KMS).

      The purpose of using a Key Management System is so access can be audited and keys easily
      rotated
      in the event of a breach. By hardcoding passwords, it will be extremely difficult to determine
      when or if, a key is compromised.

      The recommendation on which KMS to use depends on the environment the application is running
      in:

      - For Google Cloud Platform consider [Cloud Key Management](https://cloud.google.com/kms/docs)
      - For Amazon Web Services consider [AWS Key Management](https://aws.amazon.com/kms/)
      - For on premise or other alternatives to cloud providers, consider [Hashicorp's
      Vault](https://www.vaultproject.io/)
      - For other cloud providers, please see their documentation
    severity: "ERROR"
    metadata:
      shortDescription: "Use of hard-coded password"
      category: "security"
      cwe: "CWE-259"
      owasp:
        - "A2:2017-Broken Authentication"
        - "A07:2021-Identification and Authentication Failures"
      technology:
        - "kotlin"
      security-severity: "Critical"
    languages:
      - "kotlin"
