name: pacu_exploitation
category: cloud_security_assessment
tags: [exploitation_patterns, vulnerability_hunting, penetration_testing, aws, pacu]
endpoint: api/tools/pacu
description: 'Execute Pacu for AWS exploitation framework. session_name: Pacu session
  name modules: Comma-separated list of modules to run data_services: Data services
  to enumerate regions: AWS regions to target additional_args: Additional Pacu arguments'
returns: AWS exploitation framework results
parameters:
- name: session_name
  type: string
  required: false
  description: Pacu session name
  default: hexstrike_session
- name: modules
  type: string
  required: false
  description: Comma-separated list of modules to run
  default: ''
- name: data_services
  type: string
  required: false
  description: Data services to enumerate
  default: ''
- name: regions
  type: string
  required: false
  description: AWS regions to target
  default: ''
- name: additional_args
  type: string
  required: false
  description: Additional Pacu arguments
  default: ''
